spring:
  redis:
    host: 10.252.114.170 # Redis?????
    database: 0 # Redis?????????0?
    port: 6379 # Redis???????
    password: 123456 # Redis?????????????
    jedis:
      pool:
        max-idle: 6    #最大空闲数
        max-active: 10 #最大连接数
        min-idle: 2    #最小空闲数
    timeout: 2000   #连接超时